spring:
  application:
    name: guest-service
    description: guest service for my hotel application
    version : @project.version@

  h2:
    console :
      enabled : true
      path : /h2

  datasource:
    url: jdbc:h2:mem:testdb

  data:
    jpa:
      repositories:
        bootstrap-mode: default

server:
  port: 8032

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8383/eureka/
  instance:
    hostname: localhost

