server:
  port: 8001

spring:
  application:
    name: guest-service
    description: guest service for my hotel application
    version : @project.version@
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:mysql://localhost:3306/myhotel
    username : root
    password : root
  jpa:
    hibernate :
      ddl-auto : create
      show-sql : true
